User interface
sumancrest0001/ruby-tic-tac-toe pull request #2
Opened 2019-09-06 17:35 UTC by andynarf

2019-09-07 00:56 UTC, maelfosso requested changes
Hello @andynarf @sumancrest0001 

Seriously coders, your code is awesome :smile: 
But there are things that you should change and another ones that should be added.

About the ones to change, please read the comment below.
Concerning the things to add, please let me ask you a question: How are we supposed to check whether or not the mock up of the logic is OK if there is nothing concerning that ?
You should display a board with a corresponding mock up. That is, display a board, read the mark, show us how the game will loop and why not also a fake draw or win ?

Kindly make those changes and submit a new code review request.
Thanks

2019-09-07 00:56 UTC, maelfosso commented on bin/main.rb
> +  attr_accessor :player1, :player2, :current_player, :mark
`attr_accessor` is not allowed.
Use `attr_reader/attr_writers`

2019-09-07 00:56 UTC, maelfosso commented on bin/main.rb
> +  end
Please, where do you launch the game ?

2019-09-09 23:16 UTC, maelfosso requested changes
Hello coders,

# :smile:  Nice improvements. :clap: 

There are still some bugs to fix.
Look for example, I can't see any message. I got and errors when running `ruby bin/main.rb`
```ruby
$ ruby bin/main.rb 
**************************************************
*********Welcome To Our Tic-Tac-Toe Game!*********
**************************************************
==================================================
**********************RULES***********************
**    Atmost, Two players can play this game    **
**      and they mark the 3x3 grid board.       **
**   The player who manages to place mark on    **
**      all three spaces of a horizontal,       **
**   vertical, or diagonal row wins the game.   **
**   When nobody is able to do so and no more   **
**   spaces remain on the board then the game   **
** is considered as a draw. To place a mark on  **
** the grid, type the number of an empty space  **
**   that you would like to mark. Good luck!    **
**************************************************
==================================================
**************************************************
Traceback (most recent call last):
bin/main.rb:104:in `<main>': undefined method `cells' for #<Board:0x000055f97a33e450> (NoMethodError)
```
Take also a look at the the comment below, please.
I suggest you separate the class, each class into their own file. It will help you to better understand the OOP.
**`REQUIRED`** Don't forget to fix the stickler errors

Kindly make the corresponding changes and re-submit a code review request.
Thanks.

2019-09-09 23:16 UTC, maelfosso commented on lib/board_players.rb
> +  @cells = [1, 2, 3, 4, 5, 6, 7, 8, 9]
Is it a declaration of class attributes ?
If it's the case please use `attr_reader/attr_writer`.

2019-09-09 23:16 UTC, maelfosso commented on lib/board_players.rb
> +      @cell[@mark -1] == @current_player
Where did you declare `@cell` ?

2019-09-09 23:16 UTC, maelfosso commented on lib/board_players.rb
> +    @cell[@mark-1].is_a?(integer)
Where does `@mark` come from, please ?

2019-09-09 23:16 UTC, maelfosso commented on lib/board_players.rb
> +  end
Where did you declare `@current_player`, please ?

2019-09-09 23:16 UTC, maelfosso commented on lib/game_logic.rb
> +  @winner = nil
`@winner` ??
Where is it first ? Where does it come from ?

2019-09-09 23:16 UTC, maelfosso commented on lib/game_logic.rb
> +  @cell.include?(integer)
Here, you are into the `Player` class, right ?
Where does `@cell` come from ? You can't access to that here !!!

2019-09-10 00:02 UTC, andynarf commented
it wasn't pushed properly, i'm sorry you had to see that. 
My partner has the code, hopefully he'll push it tomorrow and we will resend the review.

2019-09-17 08:12 UTC, maelfosso requested changes
Hello coders,

There are some things I noticed

- [ ] I can't launch the game. `ruby bin/main.rb` doesn't display anything

- [ ] Please import the `GameLogic` into the `bin/main.rb`

- [ ] There are some instructions that is not clear. Read the comments below, please.

Also, don't complicate things and don't suppose that it will work with the logic code. It should work here without the logic.

Make the changes and make it run, please. Then submit a new code review request.
Thanks.

2019-09-17 08:12 UTC, maelfosso commented on bin/main.rb
> +  end
Please, what should I do to start the game ? `ruby bin/main.rb` doesn't display anything.

2019-09-17 08:12 UTC, maelfosso commented on bin/main.rb
> +    @game = GameLogic.new
Where does `GameLogic` come from ?

2019-09-17 08:12 UTC, maelfosso commented on bin/main.rb
> +    while @game.mark.available?(@game.mark)
That instruction is not clear.
What do you want to do here please ?

Also, don't complicate thing and don't suppose that it will work with the logic code. It should work here without the logic.

2019-09-17 08:12 UTC, maelfosso commented on bin/main.rb
> +    end
Don't you have to return something here ?

2019-09-17 23:00 UTC, maelfosso requested changes
Hello coders,

:clap:  Nice improvements. Now I can run it :smile: 

But there is still an error. Take a look on that please
```ruby
Player1, which one would you like to take: X or O ?
X
Player1, Your Symbol is X and Player2, your symbol is O
Traceback (most recent call last):
bin/main.rb:108:in `<main>': undefined method `get_mark' for #<UserInterface:0x00005639306db798> (NoMethodError)
```

- [ ] The game flow is not OK. Here are the things we should see at that step
- [OPTIONAL] game ask players for their names
- [REQUIRED] game tells which player turn it is
- [REQUIRED] game asks player to select from available moves
- [REQUIRED] game informs player if selected move is invalid
- [REQUIRED] game displays board after player move
- [REQUIRED] game informs player if selected move is a winning move
- [REQUIRED] game informs player if selected move is a draw move
- [REQUIRED] game repeats all actions for next player's move

Kindly make them appear and also correct the errors.
When done, please submit a new code review request.
Thanks

2019-09-17 23:00 UTC, maelfosso commented on bin/main.rb
> +first.get_mark
Where does `get_mark` come from please ?

2019-09-18 19:25 UTC, samgaco requested changes
#### Hi @sumancrest0001 and @andynarf :high_brightness: 

#### Everything looks well coded and like you have think it through. Try to focus on this last list of requirements that **Mael** shared before:

> * [ ]  The game flow is not OK. Here are the things we should see at that step
> * [OPTIONAL] game ask players for their names
> * [REQUIRED] game tells which player turn it is
> * [REQUIRED] game asks player to select from available moves
> * [REQUIRED] game informs player if selected move is invalid
> * [REQUIRED] game displays board after player move
> * [REQUIRED] game informs player if selected move is a winning move
> * [REQUIRED] game informs player if selected move is a draw move
> * [REQUIRED] game repeats all actions for next player's move

When running the code, one should be able to see all the required steps mocked up by your code. (See it as cheating, you ask for some names, the game asks some questions, the board is displayed after a move (the actual move doesn't need to be implemented, all of these will work only like an outline of the real project), the game shows who is the winner (again, no logic behind it)) 

For example, now running your code

```
$ ruby main.rb
```

I got:

```
**************************************************
*********Welcome To Our Tic-Tac-Toe Game!*********
**************************************************
==================================================
**********************RULES***********************
**    Atmost, Two players can play this game    **
**      and they mark the 3x3 grid board.       **
**   The player who manages to place mark on    **
**      all three spaces of a horizontal,       **
**   vertical, or diagonal row wins the game.   **
**   When nobody is able to do so and no more   **
**   spaces remain on the board then the game   **
** is considered as a draw. To place a mark on  **
** the grid, type the number of an empty space  **
**   that you would like to mark. Good luck!    **
**************************************************
==================================================
**************************************************
*****                 |   |                  *****
*****               1 | 2 | 3                *****
*****             ----+----+----             *****
*****               4 | 5 | 6                *****
*****             ----+----+----             *****
*****               7 | 8 | 9                *****
*****                 |   |                  *****
**************************************************
**************************************************
Player1, which one would you like to take: X or O ?
X
Player1, Your Symbol is X and Player2, your symbol is O
Traceback (most recent call last):
        1: from main.rb:121:in `<main>'
main.rb:109:in `play_game': undefined method `game_end' for #<GameLogic:0x0000556ad9dd10a0> (NoMethodError)

```

So when I tried to insert a symbol (and remember, the game doesn't need to actually get the symbol, it can just assign whatever symbol without taking into account the input, since what is requested in this milestone is only a sketch or a mock-up of the real project), it crashed here:

https://github.com/sumancrest0001/ruby-tic-tac-toe/blob/56968ec077b5559dc091b2bc99dc08701bf62bc4/bin/main.rb#L109

Because, as it is obvious, that method is not defined. 

I hope it is more clear this time, just try to simulate how the game would work, so when it's run it feels like how the game should be once it would be finished.

#### Please :pray: work on these and submit back. You are already on the right path with everything else.

------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-09-18 19:25 UTC, samgaco commented on bin/main.rb
> +      @game.change_players
most of these methods are yet to be defined and they are crashing the mock up implementation

2019-09-19 18:00 UTC, maelfosso approved these changes
Hello coders,

# Good job :+1: 
**Your project has been approved. You can merge !!!!** :clap: 
Good luck with the next milestone.

2019-09-19 19:30 UTC, merged

2019-09-19 19:30 UTC, sumancrest0001 commented
completed the second milestone