Readme game instructions
sumancrest0001/ruby-tic-tac-toe pull request #4
Opened 2019-09-26 17:12 UTC by sumancrest0001

Milestone-4
Improved the readme file and added the instructions

2019-09-26 19:14 UTC, maelfosso requested changes
Hello

Just one thing to correct before merging. Please indicate the correct way to start the game.
You could read the comment below.

Submit a new code review request after making the changes.
Thaks

2019-09-26 19:14 UTC, maelfosso commented on README.md
> +4. Run a command 'bin/main.rb'
please don't you think it's rather `ruby bin/main.rb` ?

2019-09-26 19:14 UTC, maelfosso commented on README.md
> +sumancrest0001 (https://github.com/sumancrest0001)
Why Are you alone on that project ?

2019-09-30 00:13 UTC, Ispirett approved these changes
Great Job  @andynarf @sumancrest0001  continue the good work.

![image](https://user-images.githubusercontent.com/38801423/62908290-41739e00-bd45-11e9-922f-6b7cf52979ee.png)
**You can merge this project now.** 

**Remember to place  descriptive commit messages.**

2019-09-30 00:13 UTC, Ispirett commented on README.md
> +## INSTRUCTION TO PLAYE THE GAME.
There is  a typo  in this line..

2019-09-30 01:56 UTC, merged